CHECKLIST_TEMPLATE = [
    # Chapter 1 - Fuselage
    {"chapter": "1", "section": "1.1", "item_key": "paintwork_skin", "item_label": "Paintwork Skin"},
    {"chapter": "1", "section": "1.1", "item_key": "condition_rivets", "item_label": "Condition of Rivets"},
    {"chapter": "1", "section": "1.1", "item_key": "hard_landings", "item_label": "Indication of Hard Landing(s)"},
    {"chapter": "1", "section": "1.1", "item_key": "turbulence_damage", "item_label": "Turbulence Damage"},
    {"chapter": "1", "section": "1.1", "item_key": "lightning_strike", "item_label": "Lightning Strike Damage"},
    {"chapter": "1", "section": "1.1", "item_key": "skin_corrosion", "item_label": "Skin Corrosion"},
    {"chapter": "1", "section": "1.1", "item_key": "flush_repairs", "item_label": "Flush Skin Repairs"},
    {"chapter": "1", "section": "1.1", "item_key": "non_flush_repairs", "item_label": "Non-Flush Skin Repairs"},
    {"chapter": "1", "section": "1.1", "item_key": "damage_outside_limits", "item_label": "Damage/Repairs Outside Limitations"},
    {"chapter": "1", "section": "1.1", "item_key": "entrance_doors", "item_label": "Entrance Doors/Seals (incl. Window)"},
    {"chapter": "1", "section": "1.1", "item_key": "service_doors", "item_label": "Service Doors/Seals (incl. Window)"},
    {"chapter": "1", "section": "1.1", "item_key": "overwing_doors", "item_label": "Overwing Doors/Exits/Seals"},
    {"chapter": "1", "section": "1.1", "item_key": "cargo_doors", "item_label": "Lower Deck Cargo Doors/Seals"},
    {"chapter": "1", "section": "1.1", "item_key": "access_panels", "item_label": "Service/Access/Compartment Doors/Panels/Seals"},
    {"chapter": "1", "section": "1.1", "item_key": "antennas", "item_label": "Antennas"},
    {"chapter": "1", "section": "1.1", "item_key": "static_ports", "item_label": "Static Ports and Probes"},
    {"chapter": "1", "section": "1.1", "item_key": "drain_masts", "item_label": "Drain Masts"},
    {"chapter": "1", "section": "1.1", "item_key": "external_lights", "item_label": "External Lights"},
    {"chapter": "1", "section": "1.1", "item_key": "exterior_placards", "item_label": "Exterior Placards & Markings"},
    {"chapter": "1", "section": "1.1", "item_key": "general_condition", "item_label": "General Condition"},
    # 1.2 Landing Gears
    {"chapter": "1", "section": "1.2", "item_key": "lg_paintwork", "item_label": "Landing Gear Paintwork"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_damage", "item_label": "Landing Gear Damage"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_corrosion", "item_label": "Landing Gear Corrosion"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_leakage", "item_label": "Landing Gear Signs of Leakage"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_doors_paint", "item_label": "Landing Gear Doors Paintwork"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_door_seals", "item_label": "Landing Gear Door Seals"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_doors_damage", "item_label": "Landing Gear Doors Damage/Repairs"},
    {"chapter": "1", "section": "1.2", "item_key": "brakes", "item_label": "Brakes (incl. Measurement in mm)"},
    {"chapter": "1", "section": "1.2", "item_key": "hyd_leakage", "item_label": "Signs of Hydraulic Leakage"},
    {"chapter": "1", "section": "1.2", "item_key": "tires", "item_label": "Tires (incl. % serviceable)"},
    {"chapter": "1", "section": "1.2", "item_key": "wheel_well", "item_label": "Wheel Well Damage/Repairs"},
    {"chapter": "1", "section": "1.2", "item_key": "landing_lights", "item_label": "Landing Lights"},
    {"chapter": "1", "section": "1.2", "item_key": "wheel_well_leaks", "item_label": "Wheel Well Signs of Hydraulic/Fuel Leakage"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_placards", "item_label": "Landing Gear Placards & Markings"},
    {"chapter": "1", "section": "1.2", "item_key": "lg_general", "item_label": "General Condition"},
    # 1.3 Empennage
    {"chapter": "1", "section": "1.3", "item_key": "emp_paintwork", "item_label": "Paintwork Skin"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_rivets", "item_label": "Condition of Rivets"},
    {"chapter": "1", "section": "1.3", "item_key": "tail_strike", "item_label": "Indication of over Rotation/Tail Strike"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_lightning", "item_label": "Lightning Strike Damage"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_corrosion", "item_label": "Skin Corrosion"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_flush_repairs", "item_label": "Flush Skin Repairs"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_non_flush", "item_label": "Non-Flush Skin Repairs"},
    {"chapter": "1", "section": "1.3", "item_key": "composite_repairs", "item_label": "Composite Repairs"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_damage_limits", "item_label": "Damage/Repairs Outside Limitations"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_lights", "item_label": "External Lights"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_placards", "item_label": "Empennage Placards & Markings"},
    {"chapter": "1", "section": "1.3", "item_key": "emp_general", "item_label": "General Condition"},
    # 1.4 Wings
    {"chapter": "1", "section": "1.4", "item_key": "wing_paintwork", "item_label": "Paintwork Skin"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_rivets", "item_label": "Condition of Rivets"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_lightning", "item_label": "Lightning Strike Damage"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_corrosion", "item_label": "Skin Corrosion"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_repairs", "item_label": "Flush/Non-Flush Skin Repairs"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_leakage", "item_label": "Signs of Hydraulic/Fuel Leakage"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_lights", "item_label": "External Lights"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_placards", "item_label": "Wing Placards & Markings"},
    {"chapter": "1", "section": "1.4", "item_key": "wing_general", "item_label": "General Condition"},
    # 1.5 Engines
    {"chapter": "1", "section": "1.5", "item_key": "eng1_cowls", "item_label": "Engine 1 - Cowls/Pylons/TR's"},
    {"chapter": "1", "section": "1.5", "item_key": "eng1_inlet", "item_label": "Engine 1 - Inlet Cowl"},
    {"chapter": "1", "section": "1.5", "item_key": "eng1_fan_blades", "item_label": "Engine 1 - Fan Blades"},
    {"chapter": "1", "section": "1.5", "item_key": "eng2_cowls", "item_label": "Engine 2 - Cowls/Pylons/TR's"},
    {"chapter": "1", "section": "1.5", "item_key": "eng2_inlet", "item_label": "Engine 2 - Inlet Cowl"},
    {"chapter": "1", "section": "1.5", "item_key": "eng2_fan_blades", "item_label": "Engine 2 - Fan Blades"},
    # Chapter 2 - Interior
    {"chapter": "2", "section": "2.2", "item_key": "cockpit_windows", "item_label": "Windows"},
    {"chapter": "2", "section": "2.2", "item_key": "cockpit_linings", "item_label": "Linings"},
    {"chapter": "2", "section": "2.2", "item_key": "cockpit_seats", "item_label": "Seats"},
    {"chapter": "2", "section": "2.2", "item_key": "instrument_panels", "item_label": "Instrument Panels"},
    {"chapter": "2", "section": "2.2", "item_key": "control_panels", "item_label": "Control Panels"},
    {"chapter": "2", "section": "2.2", "item_key": "cb_panels", "item_label": "Circuit-Breaker Panels"},
    {"chapter": "2", "section": "2.2", "item_key": "emergency_equipment", "item_label": "Emergency Equipment"},
    {"chapter": "2", "section": "2.2", "item_key": "onboard_docs", "item_label": "On-Board Documentation"},
    {"chapter": "2", "section": "2.2", "item_key": "cockpit_placards", "item_label": "Cockpit Placards & Markings"},
    {"chapter": "2", "section": "2.2", "item_key": "cockpit_general", "item_label": "General Appearance"},
    {"chapter": "2", "section": "2.3", "item_key": "cabin_doors", "item_label": "Doors"},
    {"chapter": "2", "section": "2.3", "item_key": "escape_slides", "item_label": "Escape Slides"},
    {"chapter": "2", "section": "2.3", "item_key": "attendant_seats", "item_label": "Attendant Seats including Seatbelts"},
    {"chapter": "2", "section": "2.3", "item_key": "sidewalls", "item_label": "Sidewalls"},
    {"chapter": "2", "section": "2.3", "item_key": "ceiling_panels", "item_label": "Ceiling Panels"},
    {"chapter": "2", "section": "2.3", "item_key": "overhead_bins", "item_label": "Overhead Bins/Hat racks/PSU Panels"},
    {"chapter": "2", "section": "2.3", "item_key": "cabin_windows", "item_label": "Windows"},
    {"chapter": "2", "section": "2.3", "item_key": "passenger_seats", "item_label": "Passenger Seats including Seatbelts"},
    {"chapter": "2", "section": "2.3", "item_key": "fire_blocking", "item_label": "Fire Blocking data/labels"},
    {"chapter": "2", "section": "2.3", "item_key": "life_vests", "item_label": "Life Vests"},
    {"chapter": "2", "section": "2.3", "item_key": "carpets", "item_label": "Carpets"},
    {"chapter": "2", "section": "2.3", "item_key": "cabin_emergency", "item_label": "Emergency Equipment"},
    {"chapter": "2", "section": "2.3", "item_key": "ife_audio", "item_label": "In-Flight Entertainment - Audio"},
    {"chapter": "2", "section": "2.3", "item_key": "ife_video", "item_label": "In-Flight Entertainment - Video"},
    {"chapter": "2", "section": "2.3", "item_key": "escape_path_lighting", "item_label": "Emergency Escape Path Lighting System"},
    {"chapter": "2", "section": "2.3", "item_key": "cabin_placards", "item_label": "Passenger Cabin Placards & Markings"},
    {"chapter": "2", "section": "2.3", "item_key": "cabin_general", "item_label": "General Appearance"},
    {"chapter": "2", "section": "2.5", "item_key": "galley_structure", "item_label": "Galley Structure"},
    {"chapter": "2", "section": "2.5", "item_key": "galley_ovens", "item_label": "Ovens"},
    {"chapter": "2", "section": "2.5", "item_key": "galley_boilers", "item_label": "Water Boilers/Coffeemakers"},
    {"chapter": "2", "section": "2.5", "item_key": "galley_carts", "item_label": "Food Carts"},
    {"chapter": "2", "section": "2.5", "item_key": "galley_general", "item_label": "General Appearance"},
    {"chapter": "2", "section": "2.6", "item_key": "lav_flooring", "item_label": "Lavatory Flooring, Ceiling, Side Walls, Door"},
    {"chapter": "2", "section": "2.6", "item_key": "lav_toilet", "item_label": "Toilet & Shroud"},
    {"chapter": "2", "section": "2.6", "item_key": "lav_smoke_detector", "item_label": "Smoke Detector Installation"},
    {"chapter": "2", "section": "2.6", "item_key": "lav_extinguisher", "item_label": "Fire Extinguisher Installation"},
    {"chapter": "2", "section": "2.6", "item_key": "lav_general", "item_label": "General Appearance"},
    {"chapter": "2", "section": "2.7", "item_key": "ee_computers", "item_label": "E/E Compartment Computers"},
    {"chapter": "2", "section": "2.7", "item_key": "ee_leakage", "item_label": "Signs of Water/Hydraulic Leakage"},
    {"chapter": "2", "section": "2.7", "item_key": "ee_general", "item_label": "General Condition"},
    {"chapter": "2", "section": "2.8", "item_key": "apu_installed", "item_label": "APU Installed"},
    {"chapter": "2", "section": "2.8", "item_key": "apu_leakage", "item_label": "Signs of Fluids Leakage"},
    {"chapter": "2", "section": "2.8", "item_key": "apu_start", "item_label": "APU Start Test"},
]

DEFAULT_COMPONENTS = [
    "NLG", "LH MLG", "RH MLG", "CLHMLG", "CRHMLG",
    "APU", "Engine 1", "Engine 2", "Engine 3", "Engine 4",
]

DEFAULT_SECTIONS = [
    "1.1", "1.2", "1.3", "1.4", "1.5",
    "2.2", "2.3", "2.5", "2.6", "2.7", "2.8",
]

CHAPTER_RATINGS = [
    {"key": "1.1", "label": "1.1 - Fuselage"},
    {"key": "1.2", "label": "1.2 - Landing Gears / Doors / Wheel Well"},
    {"key": "1.3", "label": "1.3 - Empennage / Horizontal Stabilizer"},
    {"key": "1.4", "label": "1.4 - Wings / Fairings"},
    {"key": "1.5", "label": "1.5 - Engines (Cowls / Pylons / TR's)"},
    {"key": "2.2", "label": "2.2 - Cockpit / Control Cabin"},
    {"key": "2.3", "label": "2.3 - Passenger Cabin"},
    {"key": "2.5", "label": "2.5 - Galleys"},
    {"key": "2.6", "label": "2.6 - Lavatories"},
    {"key": "2.7", "label": "2.7 - E/E Compartment"},
    {"key": "2.8", "label": "2.8 - APU"},
]

OVERALL_RATINGS = ["Poor", "Normal Wear", "Good condition"]
SECTION_RATINGS = ["Poor", "Normal Wear", "Good Condition", "Fair Condition", "N/A"]
